### ISSUE TITLE
Wrong keymap for OSX (and possibly for Linux and Windows)

### ISSUE THREAD

**Issue by GorgeRonde** [Foxboron/ClojureDoc-Search#1]
The original keymap is

``` json
[
    { "keys": ["cmd+shift+c"], "command": "goto_selection"}
]
```

and needs to be 

``` json
[
    { "keys": ["super+shift+c"], "command": "goto_selection"}
]
```

in order to work on OSX

I suppose sublimetext (version 2) uses super as a "meta-form" for both ctrl and cmd LinuxOrWindowsOrOSX-wise. So maybe one default keymap file is enough.

**Comment by Foxboron** [comment]
omgomgomgomogm! First time someone added an issue on one of my repos! Yay!

I'll be fixing it asap ^^

**Comment by Foxboron** [comment]
Fixed with:
049f872e62
